### ISSUE TITLE
Special characters in file/path names

### ISSUE THREAD

**Issue by tacc-desantis** [mar-file-system/GUFI#126]
Hello,

I didn't see any references to special characters in file names, so I thought it would be best to raise another issue (don't shoot the messenger, ha!).

I'm seeing messages related to opening a DB when there is a '%' in the file name (users going to user; probably doesn't know that's a reserved character in SQL):
![image](https://user-images.githubusercontent.com/127799478/230147453-bede1ecf-b05c-415a-8951-b63746d68e2c.png)

I can always weed out that particular user's path if need be.  At any rate, I figured the developers would want to know if they didn't already.

Thank you!
John DeSantis

**Comment by calccrypto** [comment]
Please give the [fix-percent](https://github.com/mar-file-system/GUFI/compare/master...fix-percent) branch a try. `%BD` is a valid hex value so sqlite is interpreting it.

**Comment by calccrypto** [comment]
Merged
