### ISSUE TITLE
FEATURE REQUEST: Add totzero to the vrsummary table

### ISSUE THREAD

**Issue by johnbent** [mar-file-system/GUFI#137]
The most recent [commit](https://github.com/mar-file-system/GUFI/commit/74a01e913e42eca326db46fa4d194ba1025559e3) adding filesize distro to gufi_stats is very cool! Thanks for adding that.

I also noticed that there are a few useful predefined bins in vrsummary such as totltk,totmtk,totltm,totmtm,totmtg,totmtt. Would it be possible to add totzero as well so we can easily see the count of zero-byte files? Also, maybe a bit more granularity in the bins? Or, is the new gufi_stats -c filesize-log2-bins actually all that is needed here. Is it just as quick to use gufi_stats to get this as it is to query those fields in vrsummary?

Also, would it be possible to add zero-size files into the gufi_stats -c filesize-log2-bins output please?

**Comment by calccrypto** [comment]
Added 0 size bin with https://github.com/mar-file-system/GUFI/commit/2f0e2a8876710f51ffd55c404a07bebdf3342171

**Comment by calccrypto** [comment]
Added `totzero` to summary and treesummary tables with https://github.com/mar-file-system/GUFI/commit/ed622831a0289876fd0b620c12a27db9043a152a

**Comment by calccrypto** [comment]
`gufi_stats -c filesize-log*-bins` is the generic way to get histograms of sizes, but it requires walking through every single row of every single entries table in the index. Calculating and stashing the value in the summary table during index creation would be faster, with a tradeoff of an increased number of columns.

**Comment by garygrider** [comment]
Should we consider another table just for histograms at the dir level so you could choose to drop these if you don’t want them?
Then we could have a view that joins them on directory inode?

From: Jason Lee ***@***.***>
Sent: Wednesday, October 4, 2023 10:19 AM
To: mar-file-system/GUFI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [mar-file-system/GUFI] FEATURE REQUEST: Add totzero to the vrsummary table (Issue #137)


gufi_stats -c filesize-log*-bins is the generic way to get histograms of sizes, but it requires walking through every single row of every single entries table in the index. Calculating and stashing the value in the summary table during index creation would be faster, with a tradeoff of an increased number of columns.

**Comment by calccrypto** [comment]
7b8ff442a966e435c04aba15405ef174accfb2cf sets this up for future expansion
