### ISSUE TITLE
FEATURE REQUEST: gufi_stats -c dirsize-log2-bins

### ISSUE THREAD

**Issue by johnbent** [mar-file-system/GUFI#138]
The new [commit](https://github.com/mar-file-system/GUFI/commit/74a01e913e42eca326db46fa4d194ba1025559e3) which adds gufi_stats -c filesize-log2-bins is awesome. Thanks so much for adding that!

Would it be possible to add a similar gufi_stats -c dirsize_log2_bins please? Or let me know if you think that's something I might be able to do. Might be a good learning exercise for me. Be nice to get my name into the git commit history for GUFI also!

**Comment by johnbent** [comment]
Note I just submitted a PR to add this. #139

**Comment by garygrider** [comment]
Did we figure out a good *time histogram”, like what are good intervals for that?  Base 4 in days or something?

Sent with BlackBerry Work
(www.blackberry.com)


From: John Bent ***@***.******@***.***>>
Date: Tuesday, Oct 03, 2023 at 10:04 PM
To: mar-file-system/GUFI ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [EXTERNAL] [mar-file-system/GUFI] FEATURE REQUEST: gufi_stats -c dirsize-log2-bins (Issue #138)


The new commit<https://urldefense.com/v3/__https://github.com/mar-file-system/GUFI/commit/74a01e913e42eca326db46fa4d194ba1025559e3__;!!Bt8fGhp8LhKGRg!DPeJOkzsBmeLU0spUNFVhnTPew7Jh-dO7i8-RNNe_jocxgDNVpHuzKJTmMSaO50oSWyShRKYmsJC6_M4IJMaVmWC$> which adds gufi_stats -c filesize-log2-bins is awesome. Thanks so much for adding that!

Would it be possible to add a similar gufi_stats -c dirsize_log2_bins please? Or let me know if you think that's something I might be able to do. Might be a good learning exercise for me. Be nice to get my name into the git commit history for GUFI also!

**Comment by johnbent** [comment]
Closing this since it is satisfied. But will create a new to discuss logitudinal study overall.
