### ISSUE TITLE
query to get Big directories with the help of GUFI db

### ISSUE THREAD

**Issue by yr-wang-hit** [mar-file-system/GUFI#152]
Wonder if there are queries to list big directories with GUFI db.
Thanks !

**Comment by calccrypto** [comment]
Hi! By "big directories", do you mean large file size, file count, or something else?

Please see [gufi_stats](https://github.com/mar-file-system/GUFI/blob/main/scripts/gufi_stats) for a list of hardcoded queries that we thought might be useful. To see those queries in action, see the [test output](https://github.com/mar-file-system/GUFI/blob/main/test/regression/gufi_stats.expected). If you do not not find what you are looking for, please let us know.

**Comment by yr-wang-hit** [comment]
Ah... Sorry for ambiguous expression.
The question is how to use gufi db to locate the directory that the sum of files size under it above some threshold.
The HPC filesystem is Lustre, with billions of files in total(about 10Pb in total). How to set the threads parameter so that we can balance the mds pressure and the efficiency when we use gufi_dir2index to generate index db for such a big fiilesystem? 

Thanks for your reply!
