### ISSUE TITLE
gufi_ls updates

### ISSUE THREAD

**Issue by dmanno** [mar-file-system/GUFI#8]
We've modified gufi_find quite a bit and gufi_ls has fallen behind some. Formatting definitely needs to be reworked to feel more like ls.

**Comment by calccrypto** [comment]
`gufi_ls path` works but `gufi_ls /path` does not

**Comment by calccrypto** [comment]
4b9bf4b7cf3def066845e6219995706c3a081a4b Removes double and trailing slashes

**Comment by calccrypto** [comment]
f3b20b7405e407b481e2c657a9e6e00ecadb68ff Adds rwx permissions, text timestamps, and size modifiers with `-h`/`--human-readable` and `--block-size`

**Comment by calccrypto** [comment]
c13597f sets the default width for the size column is 16. It can be changed with the `--size-width` option

**Comment by calccrypto** [comment]
73f6b3f5926cfc4d7c91b6db9be56a5d08efcb9c allows for `gufi_ls -R` to print directory contents (files and links only) grouped together.
