### ISSUE TITLE
Exclude .snapshot[s] directories eg GPFS

### ISSUE THREAD

**Issue by brockpalen** [mar-file-system/GUFI#92]
Feature request: When indexing systems that have publicly viewable `.snapshot` or similar paths it complicates queries or causes confusion with multiple counting files etc.

An option would be to just delete `.snapshot` after the scan but that still means that GUFI indexed that entire path.

Thanks!

**Comment by garygrider** [comment]
Seems like a stopword list for the extraction process or index build process might be handy.
Good suggestion!

Sent with BlackBerry Work
(www.blackberry.com)


From: Brock Palen ***@***.******@***.***>>
Date: Tuesday, Jun 28, 2022, 9:30 AM
To: mar-file-system/GUFI ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [EXTERNAL] [mar-file-system/GUFI] Exclude .snapshot[s] directories eg GPFS (Issue #92)


Feature request: When indexing systems that have publicly viewable .snapshot or similar paths it complicates queries or causes confusion with multiple counting files etc.

An option would be to just delete .snapshot after the scan but that still means that GUFI indexed that entire path.

Thanks!
