### ISSUE TITLE
Issue with gufi_find command

### ISSUE THREAD

**Issue by swapng** [mar-file-system/GUFI#98]
With -size option if we pass '-ve' number along with size in k, M or G then it's giving an error,

example command which I tried,
**gufi_find -size -10M**

**Comment by swapng** [comment]
**Update:**
gufi_find with '-' is working,
used **gufi_find -size=-10M**

**Comment by swapng** [comment]
Is there any way to pass the size without giving "=" sign

Like, **gufi_find -size -10M**

**Comment by calccrypto** [comment]
This is an artifact of python's argparse library. The `=` sign is needed to make sure argparse does not treat arguments starting with `-` as flags. If there is a clean way to get around it, please let us know.

**Comment by swapng** [comment]
Yes after reading the code I came to know that's behaviour from python argparser. Thank you for confirmation.
Sure I'll try to do some work around, If it's done then let you guys know.

Also I tried all options from gufi_find command, but few options like **-iname**, **-inmemory_name**, **-lname**, **-newer**, **-samefile**  are not working for me (might be missing something). 

Could you please provide me one example for each option.

Thank you once again!

**Comment by calccrypto** [comment]
`-iname "ABC"` should find all names matching `[a|A][b|B][c|C]`. c97c22de65f6e0365dce8c0c20d87aae40561cca
`-lname "ABC"` should find all links matching `ABC`. 6f019f60e4fa0352464174ca804d00af29dda359
`-newer <reference>` where reference is an actual path that can be `stat`-ed. a1ed06bf7d38a65ba46911211864b3542765114f
`-samefile <reference>` where reference is an actual path that can be `stat`-ed. 237244dc457362b2bd082c6c72a4ae4879c5db0b

`--in-memory-name` sets the name of the intermediate table used when aggregating, and generally should not be used

**Comment by swapng** [comment]
Thanks for information, i tried above options it worked.

One more thing, while running gufi_find with -name option it works for filename with no special characters.
For example,
gufi_find -name "CREDITS+10.txt"

It doesn't show file path

**Comment by calccrypto** [comment]
Please pull the latest GUFI. a8d93283c222d0fc7a6911feb21e00e501e466e9 changed `-name` to use `GLOB` instead of `REGEXP`.

**Comment by swapng** [comment]
Thanks it worked,

with `gufi_find | grep filename` , some how it didn't show any output.. because at the end of every file path null character is getting added that's why grep is failing.. verified it with `gufi_find > find.output`

**Comment by swapng** [comment]
Thanks for the confirmation!, I'll take a look in code. Might be I messed up something in the code.
