### ISSUE TITLE
gufi does not escape paths with special chars

### ISSUE THREAD

**Issue by brockpalen** [mar-file-system/GUFI#99]
If a directory tree has special chars GUFI will throw warnings and skip those files

eg `#`  or `?`

```
Cannot attach database as "tree": unable to open database: file:/tmp/GUFI/wgsa/cgillies/wonderland/home/cgillies/workspace-ggts-3.4.0.RELEASE/genevetter_backup/node_modules/bower/node_modules/inquirer/node_modules/cli-color/node_modules/es5-ext/test/reg-exp/#/replace/db.db?mode=ro

Error: no such table: entries: /tmp/GUFI/KStorageLite/2016_DropSeq_Run1445/SingleCellData/KPMP_DiseaseBiopsies/Repeats_NotUsed/S-1908-000945-B_?/Sample_1125-EO-2/SC_RNA_COUNTER_CS/SC_RNA_COUNTER/SC_RNA_ANALYZER/CHOOSE_DIMENSION_REDUCTION_OUTPUT/fork0/chnk0-udc60c05d5e/files/pca_csv/10_components/db.db: "       INSERT INTO sument select uid, name, size, atime,       CASE WHEN size > 100 * 1024 * 1024 THEN size ELSE 0 END AS oversize     FROM entries    WHERE type='f';"
```

The queries still run but the logs are reports are flooded with these messages and the data in those folders are skipped in the query.

**Comment by garygrider** [comment]
I thought we had tried about every odd character

Of course if its high in the path it would throw lots of messages, one per directory it can traverse into I guess.

Thanks for the find, we should get this fixed…

From: Brock Palen ***@***.***>
Reply-To: mar-file-system/GUFI ***@***.***>
Date: Friday, September 30, 2022 at 10:39 AM
To: mar-file-system/GUFI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [mar-file-system/GUFI] gufi does not escape paths with special chars (Issue #99)


If a directory tree has special chars GUFI will throw warnings and skip those files

eg # or ?

Cannot attach database as "tree": unable to open database: file:/tmp/GUFI/wgsa/cgillies/wonderland/home/cgillies/workspace-ggts-3.4.0.RELEASE/genevetter_backup/node_modules/bower/node_modules/inquirer/node_modules/cli-color/node_modules/es5-ext/test/reg-exp/#/replace/db.db?mode=ro



Error: no such table: entries: /tmp/GUFI/KStorageLite/2016_DropSeq_Run1445/SingleCellData/KPMP_DiseaseBiopsies/Repeats_NotUsed/S-1908-000945-B_?/Sample_1125-EO-2/SC_RNA_COUNTER_CS/SC_RNA_COUNTER/SC_RNA_ANALYZER/CHOOSE_DIMENSION_REDUCTION_OUTPUT/fork0/chnk0-udc60c05d5e/files/pca_csv/10_components/db.db: "       INSERT INTO sument select uid, name, size, atime,       CASE WHEN size > 100 * 1024 * 1024 THEN size ELSE 0 END AS oversize     FROM entries    WHERE type='f';"

The queries still run but the logs are reports are flooded with these messages and the data in those folders are skipped in the query.

**Comment by calccrypto** [comment]
Hi. [116b7a6](https://github.com/mar-file-system/GUFI/commit/116b7a67c0f1c62c58b4c0d44f42d5e7fd8fc6c1) should fix the issue. Let me know if it doesn't.

**Comment by brockpalen** [comment]
Confirmed working in the newest build.  Thanks!
